### PR TITLE
Drop vue1 support and add cssextracting

### PR DESCRIPTION
**Pull request by mgmeiner**
Hi,

I dropped vue 1 support  completely and introduced css extracting.
The styles of your component were added as inline css. Therefore it wasn't possbile to override styles in a comfortable way. 

If someone now uses your component he will have to import the css manually. I don't think that's a big problem because the user gets a lot more control about the styles.

If you apply this PR you will have to make a major release.

I also updated **webpack** and **babel**. 

Would be nice to hear what you think ;).

### CODE REVIEW

**Comment by noru** [comment]
Hi @mgmeiner, thanks for the suggestion and send changes along with it.

I totally agree with you on dropping Vue1, however in regards of css, my idea was to provide minimum built-in stylesheet and expose single entry point for those who care less about style. And I'm still leaning to it.

So would you explain more of your opinion about the "comfortable way"? I recall I do set those css selectors pretty loose in order to be overridden easily.

Looking forward to your further suggestions!

**Comment by mgmeiner** [comment]
Hi @noru, thanks for the quick reply.

The problem with the current styles is, that they are added as inline styles and i have no control about them where they will be added. They always added to the bottom. And inline styles always 'win' the css-override war. Look at the example:

extraxcssexample

The _et-wrapper_ class is from vue-easy-toast and the .toast-cstm-success should override styles of your  component. It is added after _et-wrapper_ but because the styles of vue-easy-toast are inlined it will not override the styles. I can fix it by declaring all my styles with _!important_ or also inline all the stlyes. But this is very ugly. If the css of vue-easy-toast would be extracted to separate css the user will get full control about the styles. He could even write is own styles and not reuse any of the default styles by not importing the css. 

Hope this makes it a bit more clear :)

**Comment by noru** [comment]
@mgmeiner Understood. But by simply using '.et-wrapper.toast-cstm-success' it should be ok, and no side effect. Are you planning to reuse that 'toast-cstm-success' class somewhere else?

**Comment by mgmeiner** [comment]
@noru  yes you're right, this would fix the problem too. But i don't like the concept of adding inline-styles without control about it. Many other libs extract their css too.  It's up to you.

**Comment by noru** [comment]
@mgmeiner I think I don't have to make the choice. Just build another 'lite' version without the inline css, and everybody's happy. Thanks for the feedback :)

**Comment by noru** [comment]
v1 is released

**Comment by mgmeiner** [comment]
Thanks @noru :)!

**Pull request merged**
